sdwilsh/siobrultech-protocols

setup.cfg
This was meant to be 3.7 and greater, but as-written, it is greater than 3.7.
=> Fix `python_requires`

.github/workflows/build.yml, setup.cfg
In order to support test harness changes for #15, we need to support Python 3.8 and newer.
=> Drop support for Python 3.7

siobrultech_protocols/gem/fields.py, siobrultech_protocols/gem/packets.py, siobrultech_protocols/gem/protocol.py
I was starting to add types in `greeneye-monitor` and realized that `pyright` run locally didn't pick up on type defs from this package. Adding the `py.typed` marker took care of that. Then I corrected a few mis-typed items and filled out the rest of the interface. The one untyped thing is a thing that couldn't be typed in 3.8 without breaking the build.
```
[0] > pyright --verifytypes siobrultech_protocols
npx: installed 1 in 1.766s
Package name: "siobrultech_protocols"
Package directory: "/Users/jkeljo/siobrultech-protocols/siobrultech_protocols"
Path of py.typed file: "/Users/jkeljo/siobrultech-protocols/siobrultech_protocols/py.typed"
Public modules: 5
siobrultech_protocols
siobrultech_protocols.gem
siobrultech_protocols.gem.fields
siobrultech_protocols.gem.packets …
```
=> Expose types to consumers, make more complete

siobrultech_protocols/gem/fields.py, siobrultech_protocols/gem/packets.py, tests/gem/test_fields.py, tests/gem/test_packets.py
I noticed that the wrap computation in `greeneye-monitor` was wrong, and actually so was the max value being reported by the `NumericField` class. This PR adds tests for all the `Field` classes, corrects the logic of `max`, and adds helpers for computing delta values.
=> Fix NumericField.max, add wrapping helpers

setup.cfg
I realized in later testing that `py.typed` wasn't getting included in the wheel. (I was using `pip install -e` when I first added the file, so I didn't notice.)
=> Publish py.typed as part of artifact

siobrultech_protocols/gem/api.py, tests/gem/test_api.py
While the docs do not say this, setting the packet format, the secondary
packet format, and the send interval respond with a string followed by
\r\n.
=> Fix API Setting Methods

README.md, siobrultech_protocols/gem/protocol.py, tests/gem/mock_transport.py, tests/gem/test_api.py, tests/gem/test_bidirectional_protocol.py, tests/gem/test_protocol.py
`asyncio` wants transports to be closed. However, when the transports are being created by an asyncio `Server` and passed to new `PacketProtocol` or `BidirectionalProtocol` instances, doing that requires the user of this library to do a lot of obnoxious plumbing of their own.
This PR makes it a little bit easier for them in two ways:
- `PacketProtocol` now sends a message to its associated queue when connections are made and lost, which allows the caller to keep track of active protocol instances
- `PacketProtocol` exposes a `close` method that can be used to close an active protocol
This is a breaking change, since previously the queue contained only `Packet` objects, and now it contains `PacketProtocolMessage`s instead.
Fixes #48
=> Enable callers to properly close protocol transports

siobrultech_protocols/gem/packets.py, tests/gem/test_packets.py
As suggested in #44, this adds two new methods to help consumers get the average power and pulse rate between two packets.
=> Add `get_average_power` and `get_average_pulse_rate` to `Packet`

siobrultech_protocols/gem/api.py, siobrultech_protocols/gem/protocol.py
It had been so long since I touched this code I had forgotten what these were for.  After figuring it out again, it seems prudent to document them.
This also removes an old declaration in the `protocol.py` file that is no longer used of both of these.
=> Document `T` and `R` Types

siobrultech_protocols/gem/api.py, siobrultech_protocols/gem/const.py, siobrultech_protocols/gem/protocol.py, tests/gem/test_api.py
This allows passing a new argument to a `BidirectionalProtocol` that lets the user configure the time the protocol will wait before attempting to send a command.
Should help work around the problem discussed in #84
This introduces a breaking change that removes the constant `PACKET_DELAY_CLEAR_TIME` from `siobrultech_protocols.gem.protocol`.  A new constant, `PACKET_DELAY_CLEAR_TIME_DEFAULT` is added to `siobrultech_protocols.gem.const` that is the default value we use if a value is not provided to the `BidirectionalProtocol`.
=> Allow customizing the packet clear time interval used by the library

.pre-commit-config.yaml, requirements-dev.txt
Fix pre-commit configuration
Pre-commit hooks were failing for me. There were two issues:
1. flake8 URL was to gitlab when it should have been github
2. isort needed updating (same issue as https://github.com/home-assistant/core/issues/86892)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/sdwilsh/siobrultech-protocols/pull/105).
* #108
* #107
* #106
* __->__ #105
=> Fix pre-commit configuration

.pre-commit-config.yaml, requirements-dev.txt, siobrultech_protocols/gem/packets.py, tests/gem/test_packets.py
Make pulse counters and temperature sensors optional in Packet
I'm working towards adding support for ECM-1240, which doesn't have these sensors.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/sdwilsh/siobrultech-protocols/pull/107).
* #108
* __->__ #107
* #106
* #105
=> Make pulse counters and temperature sensors optional in Packet

siobrultech_protocols/gem/protocol.py, tests/gem/test_bidirectional_protocol.py
Make the protocol more resilient to devices that ignore API calls.
The protocol was getting into an invalid state. This adds a test that
was initially failing, and then fixes the issue.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/sdwilsh/siobrultech-protocols/pull/114).
* #116
* #115
* __->__ #114
=> Make the protocol more resilient to devices that ignore API calls.

siobrultech_protocols/gem/packets.py, siobrultech_protocols/gem/protocol.py, tests/gem/test_bidirectional_protocol.py, tests/gem/test_packets.py
Add packet helpers for ECM aux channels
ECM-1240 has 5 aux channels that can take either pulse counters or CTs;
this adds packet helper for computing deltas and rates of change for those,
similar to what already exist for the CT and pulse counter channels.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/sdwilsh/siobrultech-protocols/pull/115).
* #116
* __->__ #115
* #114
=> Add packet helpers for ECM aux channels

siobrultech_protocols/gem/packets.py, tests/gem/test_packets.py
Don't divide by zero if no time has elapsed between packets
Just a bit of safety.
=> Don't divide by zero if no time has elapsed between packets

siobrultech_protocols/gem/protocol.py, tests/gem/test_bidirectional_protocol.py, tests/gem/test_protocol.py
Remove PacketProtocol.close()
I originally put this in with the idea that it was difficult for callers to keep track of transports to close them (#51). That's not really accurate, though. For `asyncio`, `loop.create_connection()` returns the transport, and the server returned by `loop.create_server()` has a `sockets` member that keeps track of all open sockets. This code snippet from `greeneye_monitor` is an example of how to close them upon shutdown:
```
for socket in self._server.sockets:
socket.shutdown(socket.SHUT_RDWR)
socket.close()
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/sdwilsh/siobrultech-protocols/pull/120).
* #126
* #125
* #124
* #123
* #122
* #121
* __->__ #120
=> Remove PacketProtocol.close()

siobrultech_protocols/gem/protocol.py
Prefactor _get_packet into _process_buffer, in anticipation of changing how BidirectionalProtocol plugs in
I'm working towards ECM-1240 API support. One difference between the GEM and ECM APIs is that the ECM API does not have a way to pause packet sends. As a result, we need to be resilient to a packet arriving while an API call is in progress.
This PR lays some groundwork for that by refactoring how `PacketProtocol` parses packets, without changing behavior yet. Rather than repeatedly calling `_get_packet`, passing along any parsed packets that result, it will now repeatedly call `_process_buffer`, which will take care of passing those packets along. The following PR will then make the small behavior change of allowing packets to come in while an API request is in progress.
---
Stack …
=> Prefactor _get_packet into _process_buffer, in anticipation of changing how BidirectionalProtocol plugs in

siobrultech_protocols/gem/protocol.py, tests/gem/test_bidirectional_protocol.py
Allow packets to interleave with API responses
I'm working towards ECM-1240 API support. One difference between the GEM and ECM APIs is that the ECM API does not have a way to pause packet sends. As a result, we need to be resilient to a packet arriving while an API call is in progress.
Previously, `BidirectionalProtocol` would intercept all incoming data once it had reached the `SENT_API_REQUEST` state (which is after the packet pause request and the subsequent delay). This PR changes it to only intercept data that `PacketProtocol` does not recognize as a packet.
The code assumes that the packets are sent atomically with respect to API responses -- that is, while a packet might interrupt an API response, no API response can interrupt a packet. That's not documented one way or another, …
=> Allow packets to interleave with API responses

README.md, siobrultech_protocols/gem/api.py, siobrultech_protocols/gem/protocol.py, tests/gem/test_api.py, tests/gem/test_bidirectional_protocol.py, tests/gem/test_protocol.py
Return API call results as soon as they arrive
Our current implementation of API calls just asks the caller to wait a few seconds and then read the response. However, GEM and ECM-1240 API responses have either a predictable length or a predictable terminator, so we can do better.
This PR changes how `BidirectionalProtocol` works. Instead of having separate methods to send a request and receive a reply, it now has one `invoke_api` method which takes an `ApiCall`, the parameters for the call, and a `Future` into which the result will be placed. Callers now `await` that `Future` with a timeout, and typically will receive a response almost immediately.
This is a breaking change for callers who use the protocol directly. Callers who use the higher-level APIs (`api.call_api` or the individual …
=> Return API call results as soon as they arrive

siobrultech_protocols/gem/protocol.py, tests/gem/test_bidirectional_protocol.py
Enable packet delay to be skipped
This PR gives the option of disabling the packet delay, while still leaving it on by default. In my own testing locally, I've seen that we can get away without sending the packet delay request, and that doing so makes GEM API calls almost instantaneous. I'd like to be able to try that out at broader scale, without requiring a new release if it turns out to not work in some cases.
=> Enable packet delay to be skipped

siobrultech_protocols/gem/api.py, siobrultech_protocols/gem/protocol.py, tests/gem/test_api.py, tests/gem/test_bidirectional_protocol.py
ECM API support
The ECM API is rather different from GEM. Instead of a single round-trip per call, each API call involves multiple round-trips. For example, in order to set the packet send interval:
1. PC sends FC (hex)
2. ECM-1240 responds with FC (hex)
3. PC sends three ASCII bytes “S” “E” “T” (must be upper case characters)
4. ECM-1240 responds with FC (hex)
5. PC sends three ASCII bytes “I” “V” “2” (must be upper case characters)
6. ECM-1240 responds with FC (hex)
7. PC sends a single byte chr$(interval value) sends the ascii character representing the interval.
8. ECM-1240 responds with FC (hex)
So that's 4 round-trips for one API call.
This PR updates `ApiCall` to allow separate formatters and parsers to be supplied for GEM and ECM, adds the necessary behaviors in …
=> ECM API support

Earthfile
The fewer files we copy, the more likely the step will be cached by Earthly, making local development time much faster.  Since requirements do not change much we can cache those expensive steps.
=> Be more discerning in what is copied over

siobrultech_protocols/gem/protocol.py, tests/gem/test_bidirectional_protocol.py, tests/gem/test_protocol.py
Turns out my reasoning on #120 was incorrect. `asyncio`'s `Server` just keeps track of the listening sockets, not the new sockets that are created for each connection. If we want to be able to close things down properly, we have to keep track of the transports ourselves.
=> Re-add close() method to protocols (Revert #120)

siobrultech_protocols/gem/fields.py, siobrultech_protocols/gem/packets.py, tests/gem/test_fields.py, tests/gem/test_packets.py
While debugging an issue, I wanted to create a fake monitor that would send packets of my own construction. To do that, I enabled Field and Packet to format values as well as parse them.
=> Enable formatting packets
